/* Generated By:JavaCC: Do not edit this line. CalculadoraConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CalculadoraConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int MULT = 7;
  /** RegularExpression Id. */
  int DIV = 8;
  /** RegularExpression Id. */
  int LPAREN = 9;
  /** RegularExpression Id. */
  int RPAREN = 10;
  /** RegularExpression Id. */
  int NUMBER = 11;
  /** RegularExpression Id. */
  int SIN = 12;
  /** RegularExpression Id. */
  int COS = 13;
  /** RegularExpression Id. */
  int TAN = 14;
  /** RegularExpression Id. */
  int ASIN = 15;
  /** RegularExpression Id. */
  int ACOS = 16;
  /** RegularExpression Id. */
  int ATAN = 17;
  /** RegularExpression Id. */
  int POT = 18;
  /** RegularExpression Id. */
  int SQRT = 19;
  /** RegularExpression Id. */
  int LOG = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "<NUMBER>",
    "\"sin\"",
    "\"cos\"",
    "\"tan\"",
    "\"asin\"",
    "\"acos\"",
    "\"atan\"",
    "\"^\"",
    "\"sqrt\"",
    "\"log\"",
  };

}
